// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
  }
}
